#!/usr/bin/env bash
# config.sh — Centralized constants for agent-sandbox
# Sourced by sandbox.sh and test suites. All values are readonly.
# shellcheck disable=SC2034  # Variables used by sourcing scripts

# --- Defaults (overridable via environment before sourcing) ---

readonly DEFAULT_SANDBOX_NAME="agent-sandbox"
readonly DEFAULT_CONFIG_DIR="${HOME}/.config/agent-sandbox"
readonly DEFAULT_KEYCHAIN_SERVICE="sops-age-key"
readonly DEFAULT_ENV_ENC=".env.enc"
readonly DEFAULT_ENV_FILE=".env"
readonly DEFAULT_NETWORK_POLICY="network-policy.json"
readonly DEFAULT_SANDBOX_MEMORY="4g"
readonly DEFAULT_SANDBOX_CPUS="2"

# --- Constants (not overridable) ---

# SOPS format flags — required because SOPS doesn't auto-detect .env/.env.enc as dotenv
readonly SOPS_FORMAT_FLAGS="--input-type dotenv --output-type dotenv"

# Placeholder key in .sops.yaml (before 'make setup' generates a real key)
readonly PLACEHOLDER_KEY="REPLACE_WITH_YOUR_AGE_PUBLIC_KEY"

# AGE key format validation regexes
readonly AGE_PRIVATE_KEY_REGEX='^AGE-SECRET-KEY-[A-Z0-9]+$'
readonly AGE_PUBLIC_KEY_REGEX='^age1[a-z0-9]+$'

# Required tools and their install instructions
# Format: "command:install_hint"
readonly REQUIRED_TOOLS=(
	"docker:Docker Desktop 4.50+ (https://docker.com/products/docker-desktop)"
	"sops:brew install sops # Latest: v3.12.1"
	"age:brew install age # Latest: v1.3.1"
	"jq:brew install jq # Latest: v1.8.1"
)

# Minimum Docker Desktop version for sandbox support
readonly DOCKER_MIN_VERSION="4.50" # Min version as of Feb 2026: 4.62.0

# Platform requirement
readonly REQUIRED_PLATFORM="Darwin"

# --- OpenCode / Model Discovery ---

# Default OpenCode config file name (generated by cmd_config)
readonly DEFAULT_OPENCODE_CONFIG="opencode.json"

# Preferred default model ID (used when available in discovered models)
# If this model exists in the API response, it will be selected as the default
readonly DEFAULT_MODEL_ID="claude_4_5_opus"

# OpenAI-compatible models endpoint path (appended to base URL)
readonly MODELS_ENDPOINT_PATH="/models"

# Default provider name for OpenAI-compatible APIs
readonly DEFAULT_PROVIDER_NAME="custom-api"

# Maximum response size for model discovery (bytes) — prevents parsing huge responses
readonly MAX_MODELS_RESPONSE_SIZE=1048576 # 1 MB

# curl timeout for model discovery (seconds)
readonly MODELS_FETCH_TIMEOUT=30
